### PR TITLE
Add share gradio argument, add -1 to random seed.

### PR DESCRIPTION
**Pull request by JimikoSK**
Adds passing --share True to share the gradio publicly.

Adds random seed if seed entered is -1.

### CODE REVIEW

**Comment by JimikoSK** [comment]
@zjp-shadow Maybe can these be merged? I found them useful.

**Comment by zjp-shadow** [comment]
> @zjp-shadow Maybe can these be merged? I found them useful.

Yes I merge there pr now. sorry for delay, because I go to Denver to attend siggraph theses days

**Comment by zjp-shadow** [comment]
Thanks a lot for your contribution to our works~ :)

**Comment by JimikoSK** [comment]
> > @zjp-shadow Maybe can these be merged? I found them useful.
> 
> Yes I merge there pr now. sorry for delay, because I go to Denver to attend siggraph theses days

Very good! I hope you had fun! I am glad to help my little way. ^^

**Pull request merged**
